---
title: "plotly"
author: "Jiayi"
date: "2024-10-22"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


Do some initial data cleaning/ subsetting

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Use plotly to make some quick plots


```{r }
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: ", price, "\nNeighborhood: ", neighbourhood)) %>% 
  plot_ly(
    x = ~lat, y = ~long,color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

next up -- box plot

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

let's do a bar chart with number of rentals

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

